{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "demo-app-iac.fullname" . }}
  labels:
    {{- include "demo-app-iac.labels" . | nindent 4 }}  
spec:
  rules:
    - host: {{ include "demo-app-iac.fullname" . }}.com 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "demo-app-iac.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{ end }}